import type { Country, Signal } from "./types";

export const COUNTRIES: Country[] = [
  {
    code: "fra",
    name: "Fransa",
    flag: "🇫🇷",
    popularCity: "Paris",
    destinationCode: "CDG",
    centers: ["İstanbul Şişli", "İstanbul Kadıköy", "Ankara", "İzmir"],
    visible: false,
    tips: [
      "Fransa vizesi için rezervasyon tarihinizden en az 3 ay önceden başvurun.",
      "Banka hesap özeti son 3 aya ait olmalı ve bakiye yeterli görünmelidir.",
      "Konaklama belgesi (otel rezervasyonu veya davet mektubu) zorunludur.",
      "Seyahat sigortası en az 30.000€ teminat içermelidir.",
      "Randevu saatine 15 dakika önce merkezde olun, geç kalırsanız iptal edilir.",
    ],
    requirements: ["Pasaport (6 ay geçerli)", "2 biyometrik fotoğraf", "Vize başvuru formu", "Seyahat sigortası", "Uçuş rezervasyonu", "Otel rezervasyonu", "Banka ekstreleri (3 ay)", "Gelir belgesi"],
    processingTime: "10-15 iş günü",
    avgWait: "45-60 gün",
  },
  {
    code: "che",
    name: "İsviçre",
    flag: "🇨🇭",
    popularCity: "Zürih",
    destinationCode: "ZRH",
    centers: ["İstanbul Şişli", "Ankara"],
    visible: false,
    tips: [
      "İsviçre, Schengen bölgesinde olmakla birlikte AB üyesi değildir; başvuru süreçleri farklıdır.",
      "Finansal kapasite göstergesi olarak günlük 90 CHF yeterliliği kanıtlanmalıdır.",
      "Biyometrik veri verimi zorunludur, ilk kez başvuranlar merkeze gelmek zorundadır.",
      "İsviçre'nin iki şehrine gitmeyi planlıyorsanız en uzun konaklamayı yaptığınız kanton belirleyicidir.",
    ],
    requirements: ["Pasaport", "Biyometrik fotoğraf", "Sigorta", "Finansal belgeler", "İstihdam belgesi", "Konaklama rezervasyonu"],
    processingTime: "15 iş günü",
    avgWait: "30-50 gün",
  },
  {
    code: "nld",
    name: "Hollanda",
    flag: "🇳🇱",
    popularCity: "Amsterdam",
    destinationCode: "AMS",
    centers: ["İstanbul Şişli", "Ankara", "İzmir"],
    visible: false,
    tips: [
      "Hollanda konsolosluğu 15 dakika geç kalınan başvuruları kabul etmez.",
      "Apostille onaylı belgelerin resmi tercümesi gerekmektedir.",
      "Giriş amacınız net olmalı: Turizm, iş, aile ziyareti ayrı destekleyici belgeler gerektirir.",
      "Parmak izi verisi 59 ay boyunca geçerlidir; bu süre içinde tekrar fiziksel başvuru gerekmez.",
    ],
    requirements: ["Pasaport", "Fotoğraf", "Sigorta", "Banka ekstresi", "Konaklama", "Uçuş rezervasyonu"],
    processingTime: "10-15 iş günü",
    avgWait: "40-55 gün",
  },
  {
    code: "nor",
    name: "Norveç",
    flag: "🇳🇴",
    popularCity: "Oslo",
    destinationCode: "OSL",
    centers: ["İstanbul Şişli", "Ankara"],
    visible: false,
    tips: [
      "Norveç'te sezon farkı belirgindir; yaz randevuları Ocak'tan itibaren tükenmektedir.",
      "Kuzey Işıkları izleme amacıyla Kasım–Mart döneminde turlar için erken başvurun.",
      "İş amaçlı seyahatlerde davet mektubu Norveçli şirketten gelmelidir.",
    ],
    requirements: ["Pasaport", "Sigorta (min. 30.000€)", "Konaklama belgesi", "Finansal kanıt", "Seyahat planı"],
    processingTime: "10-15 iş günü",
    avgWait: "35-50 gün",
  },
  {
    code: "swe",
    name: "İsveç",
    flag: "🇸🇪",
    popularCity: "Stockholm",
    destinationCode: "ARN",
    centers: ["İstanbul Şişli", "Ankara"],
    visible: false,
    tips: [
      "İsveç, birden fazla Schengen ülkesini kapsayan seyahatlerde en uzun konaklamanın yapıldığı ülke konsolosluğuna başvuru yapılmasını şart koşar.",
      "Başvuru sonuçları e-posta yerine VFS portalından takip edilir.",
      "Pasaport fotokopisi reddedilmez; orijinal pasaport mutlaka sunulmalıdır.",
    ],
    requirements: ["Pasaport (orijinal)", "Biyometrik fotoğraf", "Sigorta", "Banka ekstreleri", "İstihdam belgesi"],
    processingTime: "15 iş günü",
    avgWait: "30-45 gün",
  },
  {
    code: "mlt",
    name: "Malta",
    flag: "🇲🇹",
    popularCity: "Valletta",
    destinationCode: "MLA",
    centers: ["İstanbul Şişli", "Ankara"],
    visible: true,
    tips: [
      "Malta, İtalya ile paylaşımlı Schengen anlaşmasına sahipti; şimdi bağımsız değerlendirme yapılmaktadır.",
      "Yaz döneminde (Haziran–Ağustos) randevu bulmak zorlaşır, erkenden başvurun.",
      "Malta vizesi diğer Schengen ülkelerine göre belge incelemesi daha hızlıdır.",
      "Otel yerine Airbnb veya tatil villası kiralama belgeleri de kabul edilmektedir.",
    ],
    requirements: ["Pasaport", "2 fotoğraf", "Sigorta", "Konaklama belgesi", "Banka ekstresi", "Gelir belgesi"],
    processingTime: "7-10 iş günü",
    avgWait: "15-25 gün",
  },
  {
    code: "isl",
    name: "İzlanda",
    flag: "🇮🇸",
    popularCity: "Reykjavik",
    destinationCode: "KEF",
    centers: ["İstanbul Şişli", "Ankara"],
    visible: true,
    tips: [
      "İzlanda vize başvuruları İsveç Konsolosluğu aracılığıyla alınmaktadır.",
      "Kuzey Işıkları (Aurora Borealis) sezonu Eylül–Mart ayları arasındadır; bu dönemde randevu talebi artar.",
      "Ring Road (Yüzük Yolu) turları için kiralık araç belgesi gerekmektedir.",
      "Küçük bir ülke olduğu için vize işlemleri genellikle daha süratlidir.",
    ],
    requirements: ["Pasaport", "Sigorta", "Seyahat planı", "Araç kiralama belgesi (gerekliyse)", "Finansal belgeler"],
    processingTime: "10 iş günü",
    avgWait: "10-20 gün",
  },
  {
    code: "est",
    name: "Estonya",
    flag: "🇪🇪",
    popularCity: "Tallinn",
    destinationCode: "TLL",
    centers: ["İstanbul Şişli", "Ankara"],
    visible: true,
    tips: [
      "Estonya, dijital vize başvuru sistemiyle öne çıkan bir Schengen üyesidir.",
      "Tallinn'in tarihi şehir merkezi (eski şehir) bölgesinde kalıyorsanız konaklama belgesi kolayca düzenlenir.",
      "Balık avlama veya açıkhava aktivitesi için ek belgeler istenebilir.",
    ],
    requirements: ["Pasaport", "Fotoğraf", "Sigorta", "Konaklama", "Uçuş rezervasyonu"],
    processingTime: "5-10 iş günü",
    avgWait: "10-15 gün",
  },
  {
    code: "lva",
    name: "Letonya",
    flag: "🇱🇻",
    popularCity: "Riga",
    destinationCode: "RIX",
    centers: ["İstanbul Şişli", "Ankara"],
    visible: true,
    tips: [
      "Letonya VFS merkezleri İstanbul ve Ankara'da hizmet vermektedir.",
      "Riga, Doğu Avrupa'nın en ekonomik Schengen destinasyonlarından biridir.",
      "Yüksek sezon (Haziran–Ağustos) dışında randevu bulmak oldukça kolaydır.",
    ],
    requirements: ["Pasaport", "Sigorta", "Finansal belgeler", "Konaklama", "İstihdam belgesi"],
    processingTime: "7-10 iş günü",
    avgWait: "10-20 gün",
  },
  {
    code: "ltu",
    name: "Litvanya",
    flag: "🇱🇹",
    popularCity: "Vilnius",
    destinationCode: "VNO",
    centers: ["İstanbul Şişli", "Ankara"],
    visible: true,
    tips: [
      "Litvanya vize başvurusunda özellikle banka hesap özetinin son 6 aylık dönemi istenebilir.",
      "Vilnius Dışında Kaunas ve Klaipeda turlarını da kapsayan seyahatlerde seyahat planı netleştirilmelidir.",
    ],
    requirements: ["Pasaport", "Sigorta", "Banka ekstresi (6 ay)", "Konaklama belgesi"],
    processingTime: "7-10 iş günü",
    avgWait: "10-20 gün",
  },
  {
    code: "svn",
    name: "Slovenya",
    flag: "🇸🇮",
    popularCity: "Ljubljana",
    destinationCode: "LJU",
    centers: ["İstanbul Şişli", "Ankara"],
    visible: true,
    tips: [
      "Slovenya, Piran, Bled Gölü ve Triglav Milli Parkı gibi çeşitli cazibe merkezlerine sahip olduğundan seyahat planı önemlidir.",
      "Belge eksikliğinde yeniden başvuru hakkı verilir; doğrudan ret olmaz.",
    ],
    requirements: ["Pasaport", "Sigorta", "Konaklama", "Seyahat planı", "Finansal belgeler"],
    processingTime: "7-10 iş günü",
    avgWait: "10-20 gün",
  },
  {
    code: "hrv",
    name: "Hırvatistan",
    flag: "🇭🇷",
    popularCity: "Dubrovnik",
    destinationCode: "DBV",
    centers: ["İstanbul Şişli", "Ankara"],
    visible: true,
    tips: [
      "Hırvatistan Schengen'e Ocak 2023'te dahil oldu; eski vize bilgileri güncel olmayabilir.",
      "Yaz aylarında (Temmuz–Ağustos) Dalmaçya kıyısına olan talep yoğundur, çok önceden başvurun.",
      "Dubrovnik ve Split otellerinin erken rezervasyonu konaklama belgesi için de kritiktir.",
    ],
    requirements: ["Pasaport", "Sigorta", "Konaklama belgesi", "Uçuş rezervasyonu", "Banka ekstresi"],
    processingTime: "10-15 iş günü",
    avgWait: "20-35 gün",
  },
  {
    code: "dnk",
    name: "Danimarka",
    flag: "🇩🇰",
    popularCity: "Kopenhag",
    destinationCode: "CPH",
    centers: ["İstanbul Şişli", "Ankara"],
    visible: false,
    tips: [
      "Danimarka VFS'de parmak izi alımı zorunludur, merkezde fiziksel görünüm şarttır.",
      "Kopenhag'da tur düzenleyen ajans faturası da konaklama belgesi yerine geçebilir.",
    ],
    requirements: ["Pasaport", "Biyometrik fotoğraf", "Sigorta", "Finansal belgeler", "Konaklama"],
    processingTime: "10-15 iş günü",
    avgWait: "25-40 gün",
  },
  {
    code: "fin",
    name: "Finlandiya",
    flag: "🇫🇮",
    popularCity: "Helsinki",
    destinationCode: "HEL",
    centers: ["İstanbul Şişli", "Ankara"],
    visible: false,
    tips: [
      "Finlandiya'ya giriş amacı turistik ise kesin olmayan uçuş rezervasyonu da kabul edilmektedir.",
      "Kuzey Işıkları avcılığı için Lapland bölgesi rehberlik veya kamp belgeleri eklenmelidir.",
    ],
    requirements: ["Pasaport", "Sigorta", "Konaklama", "Finansal belgeler"],
    processingTime: "10-15 iş günü",
    avgWait: "20-35 gün",
  },
  {
    code: "aut",
    name: "Avusturya",
    flag: "🇦🇹",
    popularCity: "Viyana",
    destinationCode: "VIE",
    centers: ["İstanbul Şişli", "Ankara", "İzmir"],
    visible: false,
    tips: [
      "Avusturya vize başvurusunda kayıt yaptırma (Anmeldung) belgesi bazı durumlarda istenebilir.",
      "Viyana'ya ek olarak Salzburg veya Innsbruck planlanıyorsa seyahat güzergahı netleştirilmelidir.",
    ],
    requirements: ["Pasaport", "Sigorta", "Konaklama belgesi", "Banka ekstresi", "Uçuş rezervasyonu"],
    processingTime: "10-15 iş günü",
    avgWait: "30-45 gün",
  },
  {
    code: "bel",
    name: "Belçika",
    flag: "🇧🇪",
    popularCity: "Brüksel",
    destinationCode: "BRU",
    centers: ["İstanbul Şişli", "Ankara"],
    visible: false,
    tips: [
      "Belçika, Schengen randevularının en kısıtlı olduğu ülkeler arasındadır.",
      "Brüksel'deki AB kurumlarını ziyaret amacıyla ayrı bir davet belgesi gerekebilir.",
    ],
    requirements: ["Pasaport", "Biyometrik fotoğraf", "Sigorta", "Finansal belgeler", "Konaklama"],
    processingTime: "15 iş günü",
    avgWait: "50-70 gün",
  },
  {
    code: "bgr",
    name: "Bulgaristan",
    flag: "🇧🇬",
    popularCity: "Sofya",
    destinationCode: "SOF",
    centers: ["İstanbul Şişli", "Ankara"],
    visible: true,
    tips: [
      "Bulgaristan henüz tam Schengen üyesi değildir; hava ve deniz sınırlarında Schengen vizesi geçerlidir ancak kara sınırı ayrı uygulamaya tabidir.",
      "Karadeniz kıyısı (Burgaz, Nessebar) tatil planları için otel rezervasyonu yeterlidir.",
    ],
    requirements: ["Pasaport", "Sigorta", "Konaklama", "Finansal belgeler"],
    processingTime: "7-10 iş günü",
    avgWait: "10-20 gün",
  },
  {
    code: "lux",
    name: "Lüksemburg",
    flag: "🇱🇺",
    popularCity: "Lüksemburg Şehri",
    destinationCode: "LUX",
    centers: ["İstanbul Şişli", "Ankara"],
    visible: true,
    tips: [
      "Lüksemburg genellikle diğer Benelüks ülkeleriyle birlikte ziyaret edilir; Belçika veya Hollanda ile birleşik tur planlanabilir.",
      "Küçük bir ülke olduğu için başvuru süreçleri görece hızlıdır.",
    ],
    requirements: ["Pasaport", "Sigorta", "Konaklama", "Finansal belgeler"],
    processingTime: "7-10 iş günü",
    avgWait: "10-20 gün",
  },
  {
    code: "cze",
    name: "Çek Cumhuriyeti",
    flag: "🇨🇿",
    popularCity: "Prag",
    destinationCode: "PRG",
    centers: ["İstanbul Şişli", "Ankara"],
    visible: false,
    tips: [
      "Prag çok popüler bir destinasyon olduğundan randevu kıtlığı yoğun dönemlerde yaşanabilir.",
      "Çek Cumhuriyeti vize başvurularında banka hesap özetinin Türkçe-İngilizce apostilleli versiyonu tercih edilir.",
    ],
    requirements: ["Pasaport", "Sigorta", "Banka ekstresi", "Konaklama", "Uçuş rezervasyonu"],
    processingTime: "10-15 iş günü",
    avgWait: "25-40 gün",
  },
  {
    code: "pol",
    name: "Polonya",
    flag: "🇵🇱",
    popularCity: "Varşova",
    destinationCode: "WAW",
    centers: ["İstanbul Şişli", "Ankara", "İzmir"],
    visible: false,
    tips: [
      "Polonya; Türk başvuru sahiplerine yönelik göreceli olarak hızlı işleyen bir süreç sunmaktadır.",
      "Zakopane veya Kraków gibi iç destinasyonlar planlanıyorsa ulaşım planı ayrıca eklenmelidir.",
    ],
    requirements: ["Pasaport", "Sigorta", "Konaklama", "Finansal belgeler", "İstihdam belgesi"],
    processingTime: "10-15 iş günü",
    avgWait: "20-30 gün",
  },
];

const now = new Date();
const hoursAgo = (h: number) => new Date(now.getTime() - h * 3600000).toISOString();
const minutesAgo = (m: number) => new Date(now.getTime() - m * 60000).toISOString();

export const MOCK_SIGNALS: Signal[] = [
  // VISIBLE - Active
  {
    id: "sig-001",
    countryCode: "mlt",
    countryName: "Malta",
    flag: "🇲🇹",
    center: "İstanbul Şişli VFS",
    appointmentType: "Turistik Vize",
    slots: 3,
    foundAt: minutesAgo(42),
    isActive: true,
    popularCity: "Valletta",
    destinationCode: "MLA",
  },
  {
    id: "sig-002",
    countryCode: "isl",
    countryName: "İzlanda",
    flag: "🇮🇸",
    center: "Ankara VFS",
    appointmentType: "Turizm Vizesi",
    slots: 1,
    foundAt: hoursAgo(1.5),
    isActive: true,
    popularCity: "Reykjavik",
    destinationCode: "KEF",
  },
  {
    id: "sig-003",
    countryCode: "est",
    countryName: "Estonya",
    flag: "🇪🇪",
    center: "İstanbul Şişli VFS",
    appointmentType: "Kısa Dönem Turizm",
    slots: 4,
    foundAt: hoursAgo(2),
    isActive: true,
    popularCity: "Tallinn",
    destinationCode: "TLL",
  },
  {
    id: "sig-004",
    countryCode: "bgr",
    countryName: "Bulgaristan",
    flag: "🇧🇬",
    center: "İstanbul Şişli VFS",
    appointmentType: "Turistik Vize",
    slots: 6,
    foundAt: minutesAgo(18),
    isActive: true,
    popularCity: "Sofya",
    destinationCode: "SOF",
  },
  {
    id: "sig-005",
    countryCode: "lux",
    countryName: "Lüksemburg",
    flag: "🇱🇺",
    center: "Ankara VFS",
    appointmentType: "Turizm",
    slots: 2,
    foundAt: hoursAgo(3),
    isActive: true,
    popularCity: "Lüksemburg Şehri",
    destinationCode: "LUX",
  },
  // VISIBLE - Inactive (filled)
  {
    id: "sig-006",
    countryCode: "svn",
    countryName: "Slovenya",
    flag: "🇸🇮",
    center: "İstanbul Şişli VFS",
    appointmentType: "Turistik",
    slots: 0,
    foundAt: hoursAgo(8),
    filledAt: hoursAgo(7),
    isActive: false,
    popularCity: "Ljubljana",
    destinationCode: "LJU",
  },
  {
    id: "sig-007",
    countryCode: "lva",
    countryName: "Letonya",
    flag: "🇱🇻",
    center: "Ankara VFS",
    appointmentType: "Turistik Vize",
    slots: 0,
    foundAt: hoursAgo(12),
    filledAt: hoursAgo(11),
    isActive: false,
    popularCity: "Riga",
    destinationCode: "RIX",
  },
  // PREMIUM/BLURRED - Active
  {
    id: "sig-008",
    countryCode: "fra",
    countryName: "Fransa",
    flag: "🇫🇷",
    center: "İstanbul Şişli VFS",
    appointmentType: "Turistik Vize",
    slots: 2,
    foundAt: minutesAgo(8),
    isActive: true,
    popularCity: "Paris",
    destinationCode: "CDG",
  },
  {
    id: "sig-009",
    countryCode: "nld",
    countryName: "Hollanda",
    flag: "🇳🇱",
    center: "İstanbul Kadıköy VFS",
    appointmentType: "Turizm",
    slots: 1,
    foundAt: minutesAgo(23),
    isActive: true,
    popularCity: "Amsterdam",
    destinationCode: "AMS",
  },
  {
    id: "sig-010",
    countryCode: "nor",
    countryName: "Norveç",
    flag: "🇳🇴",
    center: "Ankara VFS",
    appointmentType: "Turistik Vize",
    slots: 3,
    foundAt: hoursAgo(0.5),
    isActive: true,
    popularCity: "Oslo",
    destinationCode: "OSL",
  },
  {
    id: "sig-011",
    countryCode: "che",
    countryName: "İsviçre",
    flag: "🇨🇭",
    center: "İstanbul Şişli VFS",
    appointmentType: "Turistik",
    slots: 2,
    foundAt: minutesAgo(55),
    isActive: true,
    popularCity: "Zürih",
    destinationCode: "ZRH",
  },
  {
    id: "sig-012",
    countryCode: "swe",
    countryName: "İsveç",
    flag: "🇸🇪",
    center: "Ankara VFS",
    appointmentType: "Turizm Vizesi",
    slots: 2,
    foundAt: hoursAgo(1),
    isActive: true,
    popularCity: "Stockholm",
    destinationCode: "ARN",
  },
];

export function getFlightLink(destinationCode: string, centerCity: string): string {
  const originCode = centerCity.toLowerCase().includes("ankara") ? "esb" : "ist";
  const oneMonthLater = new Date();
  oneMonthLater.setMonth(oneMonthLater.getMonth() + 1);
  const dateStr = oneMonthLater.toISOString().split("T")[0].replace(/-/g, "");
  return `https://www.skyscanner.net/transport/flights/${originCode}/${destinationCode.toLowerCase()}/${dateStr}/`;
}

export function getAccommodationLink(city: string): string {
  const encoded = encodeURIComponent(city);
  return `https://www.booking.com/searchresults.html?ss=${encoded}&lang=tr`;
}

export function formatTimeAgo(isoString: string): string {
  const diff = Date.now() - new Date(isoString).getTime();
  const minutes = Math.floor(diff / 60000);
  const hours = Math.floor(diff / 3600000);
  if (minutes < 60) return `${minutes} dakika önce`;
  if (hours < 24) return `${hours} saat önce`;
  return `${Math.floor(hours / 24)} gün önce`;
}
