import type { Country } from "./types";

export const COUNTRIES: Country[] = [
  // ── VFS Global ────────────────────────────────────────────
  {
    code: "fra",
    name: "Fransa",
    flag: "🇫🇷",
    popularCity: "Paris",
    destinationCode: "CDG",
    centers: ["İstanbul Şişli", "İstanbul Kadıköy", "Ankara", "İzmir"],
    centerOperator: "VFS Global",
    centerUrl: "https://visa.vfsglobal.com/tur/en/fra/",
    visible: false,
    tips: [
      "Rezervasyon tarihinden en az 3 ay önceden başvurun.",
      "Banka hesap özeti son 3 aya ait olmalı ve bakiye yeterli görünmelidir.",
      "Konaklama belgesi (otel veya davet mektubu) zorunludur.",
      "Seyahat sigortası en az 30.000€ teminat içermelidir.",
      "Randevu saatine 15 dakika önce merkezde olun.",
    ],
    requirements: ["Pasaport (6 ay geçerli)", "2 biyometrik fotoğraf", "Vize başvuru formu", "Seyahat sigortası (min. 30.000€)", "Uçuş rezervasyonu", "Otel rezervasyonu", "Banka ekstreleri (3 ay)", "Gelir belgesi"],
    processingTime: "10-15 iş günü",
    avgWait: "45-60 gün",
  },
  {
    code: "che",
    name: "İsviçre",
    flag: "🇨🇭",
    popularCity: "Zürih",
    destinationCode: "ZRH",
    centers: ["İstanbul Şişli", "Ankara"],
    centerOperator: "VFS Global",
    centerUrl: "https://visa.vfsglobal.com/tur/en/che/",
    visible: false,
    tips: [
      "İsviçre Schengen bölgesinde ancak AB üyesi değildir; başvuru süreçleri farklılık gösterebilir.",
      "Finansal kapasite için günlük 90 CHF yeterliliği kanıtlanmalıdır.",
      "İki kanton planlanıyorsa en uzun konaklamanın yapıldığı kanton belirleyicidir.",
      "Biyometrik veri verimi zorunludur, ilk kez başvuranlar merkeze gelmek zorundadır.",
    ],
    requirements: ["Pasaport", "Biyometrik fotoğraf", "Sigorta", "Finansal belgeler (90 CHF/gün)", "İstihdam belgesi", "Konaklama rezervasyonu"],
    processingTime: "15 iş günü",
    avgWait: "30-50 gün",
  },
  {
    code: "nld",
    name: "Hollanda",
    flag: "🇳🇱",
    popularCity: "Amsterdam",
    destinationCode: "AMS",
    centers: ["İstanbul Şişli", "Ankara", "İzmir"],
    centerOperator: "VFS Global",
    centerUrl: "https://visa.vfsglobal.com/tur/en/nld/",
    visible: false,
    tips: [
      "Hollanda konsolosluğu 15 dakika geç kalınan başvuruları kabul etmez.",
      "Apostille onaylı belgelerin resmi tercümesi gerekmektedir.",
      "Parmak izi verisi 59 ay boyunca geçerlidir; bu sürede tekrar fiziksel başvuru gerekmez.",
      "Giriş amacı net olmalı: turizm, iş, aile ziyareti ayrı belgeler gerektirir.",
    ],
    requirements: ["Pasaport", "Fotoğraf", "Sigorta", "Banka ekstresi", "Konaklama", "Uçuş rezervasyonu"],
    processingTime: "10-15 iş günü",
    avgWait: "40-55 gün",
  },
  {
    code: "nor",
    name: "Norveç",
    flag: "🇳🇴",
    popularCity: "Oslo",
    destinationCode: "OSL",
    centers: ["İstanbul Şişli", "Ankara"],
    centerOperator: "VFS Global",
    centerUrl: "https://visa.vfsglobal.com/tur/en/nor/",
    visible: false,
    tips: [
      "Norveç'te sezon farkı belirgindir; yaz randevuları Ocak'tan itibaren tükenmektedir.",
      "Kuzey Işıkları (Aurora) izlemek için Kasım–Mart, Lapland için ayrı belgeler istenir.",
      "İş amaçlı seyahatlerde davet mektubu Norveçli şirketten gelmelidir.",
    ],
    requirements: ["Pasaport", "Sigorta (min. 30.000€)", "Konaklama belgesi", "Finansal kanıt", "Seyahat planı"],
    processingTime: "10-15 iş günü",
    avgWait: "35-50 gün",
  },
  {
    code: "swe",
    name: "İsveç",
    flag: "🇸🇪",
    popularCity: "Stockholm",
    destinationCode: "ARN",
    centers: ["İstanbul Şişli", "Ankara"],
    centerOperator: "VFS Global",
    centerUrl: "https://visa.vfsglobal.com/tur/en/swe/",
    visible: false,
    tips: [
      "Birden fazla Schengen ülkesi planlanıyorsa en uzun konaklamanın yapıldığı ülke konsolosluğuna başvurun.",
      "Başvuru sonuçları e-posta yerine VFS portalından takip edilir.",
      "Pasaport fotokopisi reddedilmez; orijinal pasaport mutlaka sunulmalıdır.",
    ],
    requirements: ["Pasaport (orijinal)", "Biyometrik fotoğraf", "Sigorta", "Banka ekstreleri", "İstihdam belgesi"],
    processingTime: "15 iş günü",
    avgWait: "30-45 gün",
  },
  {
    code: "mlt",
    name: "Malta",
    flag: "🇲🇹",
    popularCity: "Valletta",
    destinationCode: "MLA",
    centers: ["İstanbul Şişli", "Ankara"],
    centerOperator: "VFS Global",
    centerUrl: "https://visa.vfsglobal.com/tur/en/mlt/",
    visible: true,
    tips: [
      "Malta vizesi diğer Schengen ülkelerine göre belge incelemesi daha hızlıdır.",
      "Yaz döneminde (Haziran–Ağustos) randevu bulmak zorlaşır, erkenden başvurun.",
      "Otel yerine Airbnb veya tatil villası kiralama belgeleri de kabul edilmektedir.",
    ],
    requirements: ["Pasaport", "2 fotoğraf", "Sigorta", "Konaklama belgesi", "Banka ekstresi", "Gelir belgesi"],
    processingTime: "7-10 iş günü",
    avgWait: "15-25 gün",
  },
  {
    code: "isl",
    name: "İzlanda",
    flag: "🇮🇸",
    popularCity: "Reykjavik",
    destinationCode: "KEF",
    centers: ["İstanbul Şişli", "Ankara"],
    centerOperator: "VFS Global",
    centerUrl: "https://visa.vfsglobal.com/tur/en/swe/",
    visible: true,
    tips: [
      "İzlanda vize başvuruları İsveç Konsolosluğu aracılığıyla alınmaktadır.",
      "Kuzey Işıkları sezonu Eylül–Mart; bu dönemde randevu talebi artar.",
      "Ring Road (Yüzük Yolu) turları için kiralık araç belgesi gerekmektedir.",
    ],
    requirements: ["Pasaport", "Sigorta", "Seyahat planı", "Araç kiralama belgesi", "Finansal belgeler"],
    processingTime: "10 iş günü",
    avgWait: "10-20 gün",
  },
  {
    code: "est",
    name: "Estonya",
    flag: "🇪🇪",
    popularCity: "Tallinn",
    destinationCode: "TLL",
    centers: ["İstanbul Şişli", "Ankara"],
    centerOperator: "VFS Global",
    centerUrl: "https://visa.vfsglobal.com/tur/en/est/",
    visible: true,
    tips: [
      "Estonya dijital vize başvuru sistemiyle öne çıkan Schengen üyesidir.",
      "Tallinn'in tarihi şehir merkezi için konaklama belgesi kolayca düzenlenir.",
      "Balık avlama veya açıkhava aktivitesi için ek belgeler istenebilir.",
    ],
    requirements: ["Pasaport", "Fotoğraf", "Sigorta", "Konaklama", "Uçuş rezervasyonu"],
    processingTime: "5-10 iş günü",
    avgWait: "10-15 gün",
  },
  {
    code: "lva",
    name: "Letonya",
    flag: "🇱🇻",
    popularCity: "Riga",
    destinationCode: "RIX",
    centers: ["İstanbul Şişli", "Ankara"],
    centerOperator: "VFS Global",
    centerUrl: "https://visa.vfsglobal.com/tur/en/lva/",
    visible: true,
    tips: [
      "Riga, Doğu Avrupa'nın en ekonomik Schengen destinasyonlarından biridir.",
      "Yüksek sezon (Haziran–Ağustos) dışında randevu bulmak oldukça kolaydır.",
    ],
    requirements: ["Pasaport", "Sigorta", "Finansal belgeler", "Konaklama", "İstihdam belgesi"],
    processingTime: "7-10 iş günü",
    avgWait: "10-20 gün",
  },
  {
    code: "ltu",
    name: "Litvanya",
    flag: "🇱🇹",
    popularCity: "Vilnius",
    destinationCode: "VNO",
    centers: ["İstanbul Şişli", "Ankara"],
    centerOperator: "VFS Global",
    centerUrl: "https://visa.vfsglobal.com/tur/en/ltu/",
    visible: true,
    tips: [
      "Banka hesap özetinin son 6 aylık dönemi istenebilir.",
      "Vilnius dışında Kaunas ve Klaipeda turlarını kapsayan seyahatlerde ulaşım planı eklenmelidir.",
    ],
    requirements: ["Pasaport", "Sigorta", "Banka ekstresi (6 ay)", "Konaklama belgesi"],
    processingTime: "7-10 iş günü",
    avgWait: "10-20 gün",
  },
  {
    code: "svn",
    name: "Slovenya",
    flag: "🇸🇮",
    popularCity: "Ljubljana",
    destinationCode: "LJU",
    centers: ["İstanbul Şişli", "Ankara"],
    centerOperator: "VFS Global",
    centerUrl: "https://visa.vfsglobal.com/tur/en/svn/",
    visible: true,
    tips: [
      "Slovenya; Piran, Bled Gölü ve Triglav Milli Parkı gibi çeşitli destinasyonlara sahiptir, seyahat planı önemlidir.",
      "Belge eksikliğinde yeniden başvuru hakkı verilir; doğrudan ret olmaz.",
    ],
    requirements: ["Pasaport", "Sigorta", "Konaklama", "Seyahat planı", "Finansal belgeler"],
    processingTime: "7-10 iş günü",
    avgWait: "10-20 gün",
  },
  {
    code: "hrv",
    name: "Hırvatistan",
    flag: "🇭🇷",
    popularCity: "Dubrovnik",
    destinationCode: "DBV",
    centers: ["İstanbul Şişli", "Ankara"],
    centerOperator: "VFS Global",
    centerUrl: "https://visa.vfsglobal.com/tur/en/hrv/",
    visible: true,
    tips: [
      "Hırvatistan Schengen'e Ocak 2023'te dahil oldu; eski vize bilgileri güncel olmayabilir.",
      "Yaz aylarında (Temmuz–Ağustos) Dalmaçya kıyısına talep yoğundur, çok önceden başvurun.",
    ],
    requirements: ["Pasaport", "Sigorta", "Konaklama belgesi", "Uçuş rezervasyonu", "Banka ekstresi"],
    processingTime: "10-15 iş günü",
    avgWait: "20-35 gün",
  },
  {
    code: "dnk",
    name: "Danimarka",
    flag: "🇩🇰",
    popularCity: "Kopenhag",
    destinationCode: "CPH",
    centers: ["İstanbul Şişli", "Ankara"],
    centerOperator: "VFS Global",
    centerUrl: "https://visa.vfsglobal.com/tur/en/dnk/",
    visible: false,
    tips: [
      "VFS'de parmak izi alımı zorunludur, merkeze fiziksel görünüm şarttır.",
      "Kopenhag'da tur düzenleyen ajans faturası konaklama belgesi yerine geçebilir.",
    ],
    requirements: ["Pasaport", "Biyometrik fotoğraf", "Sigorta", "Finansal belgeler", "Konaklama"],
    processingTime: "10-15 iş günü",
    avgWait: "25-40 gün",
  },
  {
    code: "fin",
    name: "Finlandiya",
    flag: "🇫🇮",
    popularCity: "Helsinki",
    destinationCode: "HEL",
    centers: ["İstanbul Şişli", "Ankara"],
    centerOperator: "VFS Global",
    centerUrl: "https://visa.vfsglobal.com/tur/en/fin/",
    visible: false,
    tips: [
      "Turistik amaçlı seyahatlerde kesin olmayan uçuş rezervasyonu da kabul edilmektedir.",
      "Lapland bölgesi (Kuzey Işıkları) için rehberlik veya kamp belgeleri eklenmelidir.",
    ],
    requirements: ["Pasaport", "Sigorta", "Konaklama", "Finansal belgeler"],
    processingTime: "10-15 iş günü",
    avgWait: "20-35 gün",
  },
  {
    code: "aut",
    name: "Avusturya",
    flag: "🇦🇹",
    popularCity: "Viyana",
    destinationCode: "VIE",
    centers: ["İstanbul Şişli", "Ankara", "İzmir"],
    centerOperator: "VFS Global",
    centerUrl: "https://visa.vfsglobal.com/tur/en/aut/",
    visible: false,
    tips: [
      "Kayıt yaptırma (Anmeldung) belgesi bazı durumlarda istenebilir.",
      "Salzburg veya Innsbruck planlanıyorsa seyahat güzergahı netleştirilmelidir.",
    ],
    requirements: ["Pasaport", "Sigorta", "Konaklama belgesi", "Banka ekstresi", "Uçuş rezervasyonu"],
    processingTime: "10-15 iş günü",
    avgWait: "30-45 gün",
  },
  {
    code: "bel",
    name: "Belçika",
    flag: "🇧🇪",
    popularCity: "Brüksel",
    destinationCode: "BRU",
    centers: ["İstanbul Şişli", "Ankara"],
    centerOperator: "VFS Global",
    centerUrl: "https://visa.vfsglobal.com/tur/en/bel/",
    visible: false,
    tips: [
      "Belçika, Schengen randevularının en kısıtlı olduğu ülkeler arasındadır.",
      "Brüksel'deki AB kurumlarını ziyaret amacıyla ayrı bir davet belgesi gerekebilir.",
    ],
    requirements: ["Pasaport", "Biyometrik fotoğraf", "Sigorta", "Finansal belgeler", "Konaklama"],
    processingTime: "15 iş günü",
    avgWait: "50-70 gün",
  },
  {
    code: "bgr",
    name: "Bulgaristan",
    flag: "🇧🇬",
    popularCity: "Sofya",
    destinationCode: "SOF",
    centers: ["İstanbul Şişli", "Ankara"],
    centerOperator: "VFS Global",
    centerUrl: "https://visa.vfsglobal.com/tur/en/bgr/",
    visible: true,
    tips: [
      "Bulgaristan hava ve deniz sınırlarında Schengen vizesi geçerlidir; kara sınırı ayrı uygulamaya tabidir.",
      "Karadeniz kıyısı (Burgaz, Nessebar) tatil planları için otel rezervasyonu yeterlidir.",
    ],
    requirements: ["Pasaport", "Sigorta", "Konaklama", "Finansal belgeler"],
    processingTime: "7-10 iş günü",
    avgWait: "10-20 gün",
  },
  {
    code: "lux",
    name: "Lüksemburg",
    flag: "🇱🇺",
    popularCity: "Lüksemburg Şehri",
    destinationCode: "LUX",
    centers: ["İstanbul Şişli", "Ankara"],
    centerOperator: "VFS Global",
    centerUrl: "https://visa.vfsglobal.com/tur/en/lux/",
    visible: true,
    tips: [
      "Lüksemburg genellikle Belçika veya Hollanda ile birleşik tur planlanır.",
      "Küçük bir ülke olduğu için başvuru süreçleri görece hızlıdır.",
    ],
    requirements: ["Pasaport", "Sigorta", "Konaklama", "Finansal belgeler"],
    processingTime: "7-10 iş günü",
    avgWait: "10-20 gün",
  },
  {
    code: "cze",
    name: "Çekya",
    flag: "🇨🇿",
    popularCity: "Prag",
    destinationCode: "PRG",
    centers: ["İstanbul Şişli", "Ankara"],
    centerOperator: "VFS Global",
    centerUrl: "https://visa.vfsglobal.com/tur/en/cze/",
    visible: false,
    tips: [
      "Prag çok popüler olduğundan randevu kıtlığı yoğun dönemlerde yaşanabilir.",
      "Banka hesap özetinin apostilleli Türkçe-İngilizce versiyonu tercih edilir.",
    ],
    requirements: ["Pasaport", "Sigorta", "Banka ekstresi", "Konaklama", "Uçuş rezervasyonu"],
    processingTime: "10-15 iş günü",
    avgWait: "25-40 gün",
  },
  {
    code: "pol",
    name: "Polonya",
    flag: "🇵🇱",
    popularCity: "Varşova",
    destinationCode: "WAW",
    centers: ["İstanbul Şişli", "Ankara", "İzmir"],
    centerOperator: "VFS Global",
    centerUrl: "https://visa.vfsglobal.com/tur/en/pol/",
    visible: false,
    tips: [
      "Polonya, Türk başvuru sahiplerine yönelik görece hızlı işleyen bir süreç sunmaktadır.",
      "Zakopane veya Kraków planlanıyorsa ulaşım planı ayrıca eklenmelidir.",
    ],
    requirements: ["Pasaport", "Sigorta", "Konaklama", "Finansal belgeler", "İstihdam belgesi"],
    processingTime: "10-15 iş günü",
    avgWait: "20-30 gün",
  },
  {
    code: "prt",
    name: "Portekiz",
    flag: "🇵🇹",
    popularCity: "Lizbon",
    destinationCode: "LIS",
    centers: ["İstanbul Şişli", "Ankara"],
    centerOperator: "VFS Global",
    centerUrl: "https://visa.vfsglobal.com/tur/en/prt/",
    visible: false,
    tips: [
      "Portekiz, Türk başvuru sahiplerine karşı görece esnek bir değerlendirme politikası izlemektedir.",
      "Lizbon dışında Porto veya Algarve planlanıyorsa bölgesel konaklama belgeleri eklenmelidir.",
    ],
    requirements: ["Pasaport", "Fotoğraf", "Sigorta", "Konaklama", "Uçuş rezervasyonu", "Banka ekstresi", "Gelir belgesi"],
    processingTime: "10-15 iş günü",
    avgWait: "20-35 gün",
  },

  // ── iDATA ─────────────────────────────────────────────────
  {
    code: "deu",
    name: "Almanya",
    flag: "🇩🇪",
    popularCity: "Berlin",
    destinationCode: "BER",
    centers: ["İstanbul Şişli", "İstanbul Anadolu", "Ankara", "İzmir", "Bursa", "Antalya"],
    centerOperator: "iData",
    centerUrl: "https://idata.com.tr/",
    visible: false,
    tips: [
      "Almanya vizesi iDATA merkezleri üzerinden alınmaktadır; VFS Global ile karıştırmayın.",
      "Belge incelemesinde en titiz Schengen ülkelerinden biridir; eksik belge reddine yol açar.",
      "İş amaçlı seyahatte Alman iş ortağından davet mektubu şarttır.",
      "Finansal yeterlilik için günlük 45–50€ karşılığı TL yeterli görülmelidir.",
      "Banka hesabınızın en az 6 aylık geçmişini sunmanız tavsiye edilir.",
    ],
    requirements: ["Pasaport (seyahat sonrası 3 ay geçerli)", "2 biyometrik fotoğraf", "Başvuru formu", "Seyahat sigortası", "Uçuş & konaklama rezervasyonu", "Banka ekstresi (6 ay)", "Gelir belgesi / iş sözleşmesi", "Vergi levhası (serbest meslek)"],
    processingTime: "10-15 iş günü",
    avgWait: "40-70 gün",
  },
  {
    code: "ita",
    name: "İtalya",
    flag: "🇮🇹",
    popularCity: "Roma",
    destinationCode: "FCO",
    centers: ["İstanbul Şişli", "İstanbul Anadolu", "Ankara", "İzmir", "Antalya", "Bursa"],
    centerOperator: "iData",
    centerUrl: "https://idata.com.tr/",
    visible: false,
    tips: [
      "İtalya vizesi iDATA merkezleri üzerinden alınmaktadır.",
      "İtalya 2026'da vize kotasını artırdı; fuar dönemleri (Ocak, Şubat, Kasım) dışında randevu bulmak kolaylaştı.",
      "Çok şehirli tur planlanıyorsa seyahat güzergahı belgesini detaylandırın.",
      "Biyometrik parmak izi ilk başvuruda merkezde alınır.",
      "Otel yerine Airbnb belgesi de konaklama kanıtı olarak kabul edilir.",
    ],
    requirements: ["Pasaport", "2 fotoğraf", "Sigorta (min. 30.000€)", "Konaklama belgesi", "Uçuş rezervasyonu", "Banka ekstresi", "Gelir belgesi"],
    processingTime: "10-15 iş günü",
    avgWait: "25-45 gün",
  },

  // ── Kosmos Vize ───────────────────────────────────────────
  {
    code: "grc",
    name: "Yunanistan",
    flag: "🇬🇷",
    popularCity: "Atina",
    destinationCode: "ATH",
    centers: ["İstanbul", "Ankara", "İzmir", "Antalya", "Bursa"],
    centerOperator: "Kosmos",
    centerUrl: "https://www.kosmosvisa.com/",
    visible: true,
    tips: [
      "Yunanistan, Schengen ülkeleri arasında randevu bulmayı en kolaylaştıranlardan biridir.",
      "Kosmos Vize; İstanbul, Ankara, İzmir, Antalya ve Bursa'da hizmet verir.",
      "Yaz sezonunda (Haziran–Ağustos) Ege adaları talebi yüksektir; önceden başvurun.",
      "Ada tatili planı varsa her ada için ayrı konaklama belgesi hazırlayın.",
      "Çok girişli (multiple-entry) vize için önceki vize geçmişinizi belgeleyin.",
    ],
    requirements: ["Pasaport (3 ay geçerli)", "2 biyometrik fotoğraf", "Sigorta (min. 30.000€)", "Uçuş rezervasyonu", "Otel / kiralık villa belgesi", "Banka ekstresi (3 ay)", "Gelir belgesi"],
    processingTime: "3-7 iş günü",
    avgWait: "10-30 gün",
  },

  // ── BLS International ─────────────────────────────────────
  {
    code: "esp",
    name: "İspanya",
    flag: "🇪🇸",
    popularCity: "Madrid",
    destinationCode: "MAD",
    centers: ["İstanbul", "Ankara"],
    centerOperator: "BLS International",
    centerUrl: "https://blsiber.com/tr/",
    visible: false,
    tips: [
      "BLS International, İspanya vize başvurularını Türkiye'de yönetmektedir.",
      "İspanya'ya ilk kez başvuranlarda biyometrik parmak izi zorunludur.",
      "Barcelona veya Endülüs gibi çok şehirli turlarda gün gün seyahat planı hazırlayın.",
      "Sigorta poliçesinin İspanya'yı da kapsadığına dair İngilizce onay belgesini ekleyin.",
      "Yaz sezonunda (Haziran–Eylül) randevu kıtlığı belirginleşir; 2-3 ay önceden harekete geçin.",
    ],
    requirements: ["Pasaport", "2 biyometrik fotoğraf", "Başvuru formu", "Sigorta (min. 30.000€)", "Uçuş & konaklama rezervasyonu", "Banka ekstresi", "Gelir belgesi"],
    processingTime: "10-15 iş günü",
    avgWait: "30-50 gün",
  },
  {
    code: "svk",
    name: "Slovakya",
    flag: "🇸🇰",
    popularCity: "Bratislava",
    destinationCode: "BTS",
    centers: ["İstanbul", "Ankara"],
    centerOperator: "BLS International",
    centerUrl: "https://blsiber.com/tr/",
    visible: true,
    tips: [
      "Slovakya vizesi BLS International merkezleri üzerinden alınmaktadır.",
      "Bratislava, Viyana'ya yakınlığı nedeniyle çift şehir turları için idealdir.",
      "Belge gereksinimleri diğer Schengen ülkeleriyle benzerdir; randevu bulma görece kolaydır.",
    ],
    requirements: ["Pasaport", "Fotoğraf", "Sigorta", "Konaklama belgesi", "Uçuş rezervasyonu", "Finansal belgeler"],
    processingTime: "7-10 iş günü",
    avgWait: "10-20 gün",
  },

  // ── AS Visa Solutions ─────────────────────────────────────
  {
    code: "hun",
    name: "Macaristan",
    flag: "🇭🇺",
    popularCity: "Budapeşte",
    destinationCode: "BUD",
    centers: ["İstanbul", "Ankara"],
    centerOperator: "AS Visa Solutions",
    centerUrl: "https://www.asvisasolutions.com/",
    visible: true,
    tips: [
      "Macaristan vizesi AS Visa Solutions merkezleri aracılığıyla alınmaktadır.",
      "Budapeşte'nin tarihi bölgeleri için güzergah planı eklenmesi başvuruyu güçlendirir.",
      "Termal turizm (Szechenyi banyosu vb.) için aktivite planı eklenebilir.",
      "Randevu bulmak diğer büyük Schengen ülkelerine kıyasla görece kolaydır.",
    ],
    requirements: ["Pasaport", "Fotoğraf", "Sigorta", "Konaklama belgesi", "Uçuş rezervasyonu", "Banka ekstresi", "Gelir belgesi"],
    processingTime: "7-10 iş günü",
    avgWait: "10-25 gün",
  },
];

export function formatTimeAgo(isoString: string): string {
  const diff = Date.now() - new Date(isoString).getTime();
  const minutes = Math.floor(diff / 60000);
  const hours = Math.floor(diff / 3600000);
  if (minutes < 60) return `${minutes} dakika önce`;
  if (hours < 24) return `${hours} saat önce`;
  return `${Math.floor(hours / 24)} gün önce`;
}
